- hosts: target
  become: true
  tasks:
    - name: create new deployment
      command: kubectl apply -f /home/ubuntu/myapp1.yml
    - name: create new service
      command: kubectl apply -f /home/ubuntu/service.yml
